EhkBackend.ui/Controllers/M_detail1Controller.cs
using EhkBackend.BLL;
using EhkBackend.IBLL;
using EhkBackend.ui.Common;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;

namespace EhkBackend.ui.Controllers
{
    public class M_detail1Controller : Controller
    {

        IM_detail1Service mdService = new M_detail1Service();
        // GET: M_detail1
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult mdetail1Index()
        {
            return View();
        }
        public ActionResult mdetailList()
        {
            int pageIndex = Request["Page"] == null ? 1 : int.Parse(Request["page"]);
            int pageSize = Request["rows"] == null ? 10 : int.Parse(Request["rows"]);
            int total = 0;

            var data = mdService.LoadPageEntities(pageIndex, pageSize, out total, md => true, true, md => md.account);
            var result = new { total = total, rows = data.ToList() };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult importExDetail(HttpPostedFileBase file)
        {
            var fileName = file.FileName;
            var filePath = Server.MapPath(string.Format("~/{0}", "FileExecel"));
            string path = Path.Combine(filePath, fileName);
            file.SaveAs(path);

            DataTable excelTable = new DataTable();

            excelTable = imExpro.GetExcelDataTable(path);

            DataTable dtable = new DataTable();
            dtable.Columns.Add("account");
            dtable.Columns.Add("billno");
            dtable.Columns.Add("actcode1");
            dtable.Columns.Add("chargeamt1");
            dtable.Columns.Add("actcode2");
            dtable.Columns.Add("chargeamt2");
            dtable.Columns.Add("actcode3");
            dtable.Columns.Add("chargeamt3");
            dtable.Columns.Add("actcode4");
            dtable.Columns.Add("chargeamt4");
            dtable.Columns.Add("actcode5");
            dtable.Columns.Add("chargeamt5");
            dtable.Columns.Add("actcode6");
            dtable.Columns.Add("chargeamt6");
            dtable.Columns.Add("actcode7");
            dtable.Columns.Add("chargeamt7");
            dtable.Columns.Add("actcode8");
            dtable.Columns.Add("chargeamt8");
            dtable.Columns.Add("actcode9");
            dtable.Columns.Add("chargeamt9");


            for (int i = 0; i < excelTable.Rows.Count; i++)
            {
                DataRow dr = excelTable.Rows[i];
                DataRow dr_ = dtable.NewRow();
                dr_["account"] = dr["account"];
                dr_["billno"] = dr["billno"];
                dr_["actcode1"] = dr["actcode1"];
                dr_["chargeamt1"] = dr["chargeamt1"];
                dr_["actcode2"] = dr["actcode2"];
                dr_["chargeamt2"] = dr["chargeamt2"];
                dr_["actcode3"] = dr["actcode3"];
                dr_["chargeamt3"] = dr["chargeamt3"];
                dr_["actcode4"] = dr["actcode4"];
                dr_["chargeamt4"] = dr["chargeamt4"];
                dr_["actcode5"] = dr["actcode5"];
                dr_["chargeamt5"] = dr["chargeamt5"];
                dr_["actcode6"] = dr["actcode6"];
                dr_["chargeamt6"] = dr["chargeamt6"];
                dr_["actcode7"] = dr["actcode7"];
                dr_["chargeamt7"] = dr["chargeamt7"];
                dr_["actcode8"] = dr["actcode8"];
                dr_["chargeamt8"] = dr["chargeamt8"];
                dr_["actcode9"] = dr["actcode9"];
                dr_["chargeamt9"] = dr["chargeamt9"];
                dtable.Rows.Add(dr_);

            }

            string constr = System.Configuration.ConfigurationManager.AppSettings["EFeesEntities"];
            using (TransactionScope tran = new TransactionScope())
            {
                string sql = "delete  from m_detail1";//导入 新的mdetail1
                SqlHelp.ExecuteNonQuery(constr, sql);
                DataTableSql.SqlBulkCopyByDatatable(constr, "m_detail1", dtable);

                tran.Complete();
            }
            return Content(fileName.ToString());
        }
    }
}

EhkBackend.ui/Views/M_detail1/mdetail1Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>导入M_detail1数据</title>


    <link href="~/Content/js/jquery-easyui-1.5.3/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/js/jquery-easyui-1.5.3/themes/icon.css" rel="stylesheet" />

    <link href="~/Content/css/main.css" rel="stylesheet" />

</head>
<body>
    <div class="easyui-layout" data-options="fit:true" id="useBox">
        <!--左侧树-->

        <div data-options="region:'center',split:true">
            <!--表格查询-->
            <div class="tableFind">
                @using (Html.BeginForm("importExDetail", "M_detail1", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <input name="file" type="file" id="=file" />
                    <input name="submit" id="submit" type="submit" value="导入" />
                }
                <p hidden="hidden">
                    <label>用户名;</label><input type="text" id="user" /><label>日期;</label><input type="text" id="dd" class="easyui-datebox" style="width: 16%;height:26px;" /><label>类型;</label><select>
                        <option>全部</option>
                    </select><label>关键字;</label><input type="text" />
                </p>
                <p hidden="hidden"><label>部门;</label><input type="text" id="part" /><label>选择种类：</label><input type="text" id="combox"><a id="btn" href="javascript:" class="easyui-linkbutton tableFindBut" data-options="iconCls:'icon-search'" onclick="obj.find()">查询</a></p>
            </div>
            @*<div id="sp">
                    <div style="color:#99BBE8;background:#fafafa;padding:5px;">Select a language</div>
                    <div style="padding-top:10px">
                        <input type="radio" name="lang" value="01"><span>Java</span><br />
                        <input type="radio" name="lang" value="02"><span>C#</span><br />
                        <input type="radio" name="lang" value="03"><span>Ruby</span><br />
                        <input type="radio" name="lang" value="04"><span>Basic</span><br />
                        <input type="radio" name="lang" value="05"><span>Fortran</span>
                    </div>
                </div>*@
            <!--表格列表-->
            <div class="tableCon">
                <table id="table" class="tableStyle"></table>
                <div id="tabelBut">
                    <div>
                        <a href="#" class="easyui-linkbutton" plain="true" iconCls="icon-add" onclick="obj.addBox()">新增</a>
                        <a href="#" class="easyui-linkbutton" plain="true" iconCls="icon-edit">修改</a>
                        <a href="#" class="easyui-linkbutton" plain="true" iconCls="icon-remove" onclick="obj.del()">删除</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--//新增弹出框-->
    <div id="addBox">
        <form id="addForm" method="post">
            <div class="formDiv"><label>用户名称:</label><input type="text" id="name" class="easyui-validatebox" name="name" data-options="required:true"><span class="formSpan">*</span></div>
            <div class="formDiv"><label>密码:</label><input type="password" id="pass" class="easyui-validatebox" name="pass" data-options="required:true"><span class="formSpan">*</span></div>
            <div class="formDiv"><label>入职时间:</label><input type="text" id="time" class="easyui-datebox" name="time" style="width: 70%;height: 26px"></div>
            <div class="formDiv"><label>所属部门:</label><input type="text" id="part01" /></div>
            <div class="formDiv"><label>所属角色:</label><select id="role"><option>xxxx</option></select></div>
            <div class="forSubmint"> <a href="#" class="easyui-linkbutton" iconCls="icon-ok" onclick="obj.sum()">提交</a><a href="#" class="easyui-linkbutton" iconCls="icon-redo">重置</a> </div>

        </form>
    </div>
    <!--物流详情查看-->
    <div id="lookTail">
        <div class="floatLeft maginTop ">
            <div class="lookTailDiv01">2017-12-18</div>
            <div class="floatRight maginRt">
                <span class="circleStyle01"></span>
            </div>

            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>

            <div class="clear"></div>
            <div class="lookTailDiv02">16:22:35</div>
            <div class="floatRight maginRt">
                <span class="circleStyle02 backGreen "></span>
            </div>

            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>
            <div class="clear"></div>
            <div class="lookTailDiv02">16:22:35</div>
            <div class="floatRight maginRt">
                <span class="circleStyle02 backRed "></span>
            </div>
            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>
            <div class="clear"></div>
            <div class="lookTailDiv01">2017-12-19</div>
            <div class="floatRight maginRt">
                <span class="circleStyle01"></span>
            </div>

            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>

            <div class="clear"></div>
            <div class="lookTailDiv02">16:22:35</div>
            <div class="floatRight maginRt">
                <span class="circleStyle02 backGreen "></span>
            </div>

            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>
            <div class="clear"></div>
            <div class="lookTailDiv01">2017-12-20</div>
            <div class="floatRight maginRt">
                <span class="circleStyle01"></span>
            </div>

            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>

            <div class="clear"></div>
            <div class="lookTailDiv02">16:22:35</div>
            <div class="floatRight maginRt">
                <span class="circleStyle02 backGreen "></span>
            </div>
            <div class="clear"></div>
            <div class="floatRight maginRt">
                <span class="lineH magingLeft"></span>
            </div>
        </div>

        @*<div class="floatLeft maginTop">
            <div class="divBorder magintTop01 floatLeft borderGreen"><span class="footBlood">张立新</span><span class="colorCCC">(买方)</span><span class="footBlood">下单</span></div>
            <div class="clear"></div>
            <div class="divBorder magintTop02  floatLeft borderRed"><span class="footBlood">刘强</span><span class="colorCCC">(卖方)</span><span class="footBlood">确认订单</span></div>
            <div class="clear"></div>
            <div class="divBorder magintTop03  floatLeft borderGreen"><span class="footBlood">罗林</span><span class="colorCCC">(配送员)</span><span class="footBlood">确认订单</span><span>成都市高新区西南仓库中心</span><span class="colorGreen">13695632156</span></div>
            <div class="clear"></div>
            <div class="divBorder magintTop03  floatLeft borderGreen"><span class="footBlood">罗林</span><span class="colorCCC">(配送员)</span><span class="footBlood">确认订单</span><span>成都市高新区西南仓库中心</span><span class="colorGreen">13695632156</span></div>
        </div>*@
    </div>



    <script src="~/Content/js/jquery-easyui-1.5.3/jquery.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <script src="~/Content/js/jquery-easyui-1.5.3/jquery.easyui.min.js"></script>
    <script src="~/Content/js/jquery-easyui-1.5.3/locale/easyui-lang-zh_CN.js"></script>
    <script src="~/Content/Mdetail1.js"></script>

    @*<script src="js/table.js"></script>*@


</body>
</html>